feat15: matrices extension

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -24,9 +24,9 @@ jobs:
         uses: actions/setup-node@v6
         with:
           node-version: ${{ matrix.node-version }}
-      - name: Fail if experimental
-        if: matrix.tag == 'experimental'
-        run: exit 1
+      # - name: Fail if experimental
+      #   if: matrix.tag == 'experimental'
+      #   run: exit 1
       - name: Perform some tests
         run: |
           echo "Running some tests on ${{ matrix.os }} with node version ${{ matrix.node-version }}"
